[tool.poetry]
name = "fi-utils"
version = "0.1.2"
description = ""
authors = ["Mike Babb <mike7400@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.10"
PyYAML = "^5.3.1"
google-auth-httplib2 = "^0.0.4"
SQLAlchemy = "^1.3.20"
mysql-connector-python = "^8.0.22"
google-auth-oauthlib = "^0.4.2"
google-api-python-client = "^1.12.8"
requests = "^2.25.1"
PyMySQL = "^1.0.2"
mypy = "^0.790"

[tool.poetry.dev-dependencies]
black = "^20.8b1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
