[tool.poetry]
name = "qualtrics-utils"
version = "0.5.8"
description = "Utilities for qualtrics surveys."
authors = ["Mike Babb <mike7400@gmail.com>"]
readme = "README.md"
keywords = ["qualtrics"]
license = "MIT"
repository = "https://github.com/mkbabb/qualtrics-utils"


[tool.poetry.dependencies]
python = "^3.11"
pandas = "^2.0.3"
requests = "^2.31.0"
sqlalchemy = "^2.0.20"
numpy = "^1.25.2"
googleapiutils2 = "^0.11.1"

[tool.poetry.group.dev.dependencies]
openapi-python-client = "^0.15.1"
mypy = "^1.5.1"
black = "^23.7.0"
types-requests = "^2.31.0.2"
pytest = "^7.4.0"
pymysql = "^1.1.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
