[tool.poetry]
name = "qualtrics-utils"
version = "0.5.8"
description = "Utilities for qualtrics surveys."
authors = ["Mike Babb <mike7400@gmail.com>"]
readme = "README.md"
keywords = ["qualtrics"]
license = "MIT"
repository = "https://github.com/mkbabb/qualtrics-utils"


[tool.poetry.dependencies]
python = "^3.10"
pandas = "^2.0.2"
requests = "^2.31.0"

[tool.poetry.group.dev.dependencies]
numpy = "^1.24.3"
googleapiutils2 = "^0.8.5"
mypy = "^1.3.0"
black = "^23.3.0"
types-requests = "^2.31.0.1"
pytest = "^7.3.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
