[tool.poetry]
name = "qualtrics-utils"
version = "0.6.1"
description = "Utilities for qualtrics surveys."
authors = ["Mike Babb <mike7400@gmail.com>"]

readme = "README.md"
keywords = ["qualtrics", "qualtrics-api", "qualtrics-util"]
license = "MIT"
repository = "https://github.com/mkbabb/qualtrics-utils"


[tool.poetry.dependencies]
python = "^3.10"
pandas = "^2.1.3"
requests = "^2.31.0"
sqlalchemy = "^2.0.23"
numpy = "^1.26.2"
googleapiutils2 = "^0.11.1"
loguru = "^0.7.2"

[tool.poetry.group.dev.dependencies]
openapi-python-client = "^0.15.1"
mypy = "^1.7.0"
black = "^23.11.0"
types-requests = "^2.31.0.10"
pytest = "^7.4.3"
pymysql = "^1.1.0"
pandas-stubs = "^2.1.1.230928"

[[tool.mypy.overrides]]
module = "google.*,google_auth_oauthlib.*"
ignore_missing_imports = true

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
